name: "README Translation Sync"
description: "Automatically sync README translations using GitHub Models AI"
author: "zrr-lab"

branding:
  icon: "globe"
  color: "blue"

inputs:
  source-file:
    description: "Source README file to translate"
    required: false
    default: "README.md"
  target-file:
    description: "Target translated README file"
    required: false
    default: "README.zh-CN.md"
  target-language:
    description: "Target language for translation"
    required: false
    default: "Chinese"
  model:
    description: "GitHub Models model to use"
    required: false
    default: "openai/gpt-4o-mini"
  token:
    description: "GitHub token with models:read permission"
    required: false
    default: ${{ github.token }}
  github-token:
    description: "GitHub token with models:read permission (deprecated, use token instead)"
    required: false
  max-tokens:
    description: "Maximum number of tokens to generate"
    required: false
    default: "8192"

outputs:
  has-changes:
    description: "Whether the translation has changes"
    value: ${{ steps.check-changes.outputs.has_changes }}

runs:
  using: "composite"
  steps:
    - name: Check source file changes
      id: check
      shell: bash
      run: |
        if git diff --name-only HEAD~1 HEAD 2>/dev/null | grep -q "^${{ inputs.source-file }}$"; then
          echo "changed=true" >> $GITHUB_OUTPUT
          # git diff HEAD~1 HEAD -- "${{ inputs.source-file }}" > "$RUNNER_TEMP/readme_diff.txt"
          # echo "diff_file=$RUNNER_TEMP/readme_diff.txt" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Translate using AI Inference
      if: steps.check.outputs.changed == 'true'
      id: translate
      uses: actions/ai-inference@v2
      with:
        token: ${{ inputs.github-token || inputs.token }}
        model: ${{ inputs.model }}
        max-tokens: ${{ inputs.max-tokens }}
        system-prompt: |
          You are a professional translator. Your task is to update the TARGET_LANGUAGE translation of a README.md file based on incremental changes.
          CRITICAL OUTPUT RULES:
          - Output ONLY the raw markdown content directly.
          - DO NOT wrap your output in ```markdown or any other code blocks.
          - DO NOT add any explanations, comments, or notes before or after the content.
          - Start your response directly with the markdown content.

          Translation Instructions:
          - Keep all markdown formatting, code blocks, links, and technical terms intact.
          - Add language switch links at the top: [English](SOURCE_FILE) | [TARGET_LANGUAGE](TARGET_FILE)
          - Only translate natural language text, not code, URLs, or file paths.
          - Maintain the same structure and formatting as the original.

          Incremental Update Strategy:
          - Focus on the diff provided - only modify the parts that have changed.
          - Preserve the existing translation for unchanged sections.
          - If a section was added, translate only the new section.
          - If a section was modified, update only that section's translation.
          - If a section was deleted, remove the corresponding translation.
        # prompt: ${{steps.check.outputs.diff_file}}
        prompt-file: ${{ inputs.source-file }}

    - name: Process and save translation
      if: steps.check.outputs.changed == 'true'
      shell: bash
      run: |
        # Get response from response-file (preferred) or response output
        if [ -n "${{ steps.translate.outputs.response-file }}" ] && [ -f "${{ steps.translate.outputs.response-file }}" ]; then
          RESPONSE_FILE="${{ steps.translate.outputs.response-file }}"
        else
          # Fallback: write response output to temp file for processing
          RESPONSE_FILE="$RUNNER_TEMP/translation-response.txt"
          echo "${{ steps.translate.outputs.response }}" > "$RESPONSE_FILE"
        fi

        # Read the response content
        TRANSLATED_CONTENT=$(cat "$RESPONSE_FILE")

        # Clean up potential markdown code block wrapping from AI output
        # Remove leading ```markdown, ```md, or ```
        TRANSLATED_CONTENT=$(echo "$TRANSLATED_CONTENT" | sed -E '1s/^```(markdown|md)?//')
        # Remove trailing ```
        TRANSLATED_CONTENT=$(echo "$TRANSLATED_CONTENT" | sed -E '$s/```$//')
        # Trim leading and trailing whitespace
        TRANSLATED_CONTENT=$(echo "$TRANSLATED_CONTENT" | sed -e '1s/^[[:space:]]*//' -e '$s/[[:space:]]*$//')

        # Ensure the file ends with a newline
        if [ -n "$TRANSLATED_CONTENT" ] && [ "${TRANSLATED_CONTENT: -1}" != $'\n' ]; then
          TRANSLATED_CONTENT="$TRANSLATED_CONTENT"$'\n'
        fi

        # Write to target file (preserve newlines)
        printf '%s' "$TRANSLATED_CONTENT" > "${{ inputs.target-file }}"

    - name: Check for changes
      if: steps.check.outputs.changed == 'true'
      id: check-changes
      shell: bash
      run: |
        if git diff --quiet "${{ inputs.target-file }}" 2>/dev/null; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi
